public static class ContractCodeQualifiers
{
    public static readonly Dictionary<string, string> Descriptions = new Dictionary<string, string>
    {
        { "1", "Discount Agreement" },
        { "2", "Capitation" },
        { "3", "Per Diem" },
        { "4", "Case Rate" },
        { "5", "Sole Source" },
        { "6", "Bundled Case Rate" },
        { "7", "Professional Services Agreement" },
        { "8", "Specialty Pharmacy Agreement" },
        { "9", "Carve-Out Agreement" },
        { "10", "Global Payment" },
        { "11", "Episode of Care" },
        { "12", "Warranty" },
        { "13", "Incentive Program" },
        { "14", "Accountable Care Organization (ACO)" },
        { "15", "Patient-Centered Medical Home (PCMH)" },
        { "16", "Narrow Network" },
        { "17", "Reference-Based Pricing" },
        { "18", "Pay-for-Performance (P4P)" },
        { "19", "Gain Sharing" },
        { "20", "Risk Sharing" },
        { "21", "Integrated Delivery System (IDS)" },
        { "22", "Managed Care Organization (MCO)" },
        { "23", "Pharmacy Benefit Manager (PBM)" },
        { "24", "Preferred Provider Organization (PPO)" },
        { "25", "Health Maintenance Organization (HMO)" },
        { "26", "Accountable Care Partnership" },
        { "27", "Patient-Centered Specialty Practice (PCSP)" },
        { "28", "Bundled Payment for Care Improvement (BPCI)" },
        { "29", "Comprehensive Primary Care Plus (CPC+)" },
        { "30", "Medicare Shared Savings Program (MSSP)" },
        { "31", "Next Generation ACO Model" },
        { "32", "Direct Contracting Entity (DCE)" },
        { "33", "Kidney Care Choices (KCC) Model" },
        { "34", "Primary Care First (PCF) Model" },
        { "35", "Radiation Oncology (RO) Model" },
        { "36", "Emergency Triage, Treat, and Transport (ET3) Model" },
        { "37", "Opioid Use Disorder (OUD) Treatment" },
        { "38", "Rural Community Hospital Demonstration" },
        { "39", "Maryland Total Cost of Care Model" },
        { "40", "Pennsylvania Rural Health Model" },
        { "41", "Vermont All-Payer ACO Model" },
        { "42", "Washington State Integrated Managed Care" },
        { "43", "Comprehensive Kidney Care Contracting (CKCC)" },
        { "44", "Geographic Direct Contracting Model" },
        { "45", "Community Health Access and Rural Transformation (CHART) Model" },
        { "46", "Value-Based Insurance Design (VBID) Model" },
        { "47", "Radiation Oncology Advanced APM" },
        { "48", "Kidney Care First" },
        { "49", "Comprehensive Kidney Care Contracting – Global" },
        { "50", "Comprehensive Kidney Care Contracting – Professional" },
        { "51", "Oncology Care First" },
        { "52", "Specialty Care First" },
        { "53", "Direct Contracting Global" },
        { "54", "Direct Contracting Professional" },
        { "55", "Direct Contracting Geographic" },
        { "56", "Durable Medical Equipment, Prosthetics, Orthotics, and Supplies (DMEPOS) Competitive Bidding Program" },
        { "57", "Inpatient Rehabilitation Facility (IRF) Quality Reporting Program" },
        { "58", "Long-Term Care Hospital (LTCH) Quality Reporting Program" },
        { "59", "Skilled Nursing Facility (SNF) Quality Reporting Program" },
        { "60", "Home Health Quality Reporting Program" },
        { "61", "Hospice Quality Reporting Program" },
        { "62", "Outpatient Quality Reporting Program" },
        { "63", "Inpatient Psychiatric Facility (IPF) Quality Reporting Program" },
        { "64", "Ambulatory Surgical Center (ASC) Quality Reporting Program" },
        { "65", "Hospital Outpatient Quality Reporting Program" },
        { "66", "Hospital Inpatient Quality Reporting Program" },
        { "67", "Comprehensive Care for Joint Replacement (CJR) Model" },
        { "68", "Bundled Payments for Care Improvement (BPCI) Advanced" },
        { "69", "Oncology Care Model (OCM)" },
        { "70", "Kidney Care Choices (KCC) Model - Kidney Care First" },
        { "71", "Kidney Care Choices (KCC) Model - Comprehensive Kidney Care Contracting - Global" },
        { "72", "Kidney Care Choices (KCC) Model - Comprehensive Kidney Care Contracting - Professional" },
        { "73", "Radiation Oncology (RO) Model" },
        { "74", "Emergency Triage, Treat, and Transport (ET3) Model" },
        { "75", "Opioid Use Disorder Treatment" },
        { "76", "Maryland Total Cost of Care Model - Care Transformation Initiatives" },
        { "77", "Maryland Total Cost of Care Model - Global Budget Revenue" },
        { "78", "Pennsylvania Rural Health Model" },
        { "79", "Vermont All-Payer ACO Model" },
        { "80", "Washington State Integrated Managed Care" },
        { "81", "Community Health Access and Rural Transformation (CHART) Model - Community Transformation Track" },
        { "82", "Community Health Access and Rural Transformation (CHART) Model - Community Transformation Track - ACO" },
        { "83", "Community Health Access and Rural Transformation (CHART) Model - Community Transformation Track - Other" },
        { "84", "Value-Based Insurance Design (VBID) Model" },
        { "85", "Radiation Oncology Advanced Alternative Payment Model" },
        { "86", "Oncology Care First Model" },
        { "87", "Specialty Care First Model" },
        { "88", "Direct Contracting Model - Global" },
        { "89", "Direct Contracting Model - Professional" },
        { "90", "Direct Contracting Model - Geographic" },
        { "91", "Durable Medical Equipment, Prosthetics, Orthotics, and Supplies (DMEPOS) Competitive Bidding Program" },
        { "92", "Inpatient Rehabilitation Facility (IRF) Quality Reporting Program" },
        { "93", "Long-Term Care Hospital (LTCH) Quality Reporting Program" },
        { "94", "Skilled Nursing Facility (SNF) Quality Reporting Program" },
        { "95", "Home Health Quality Reporting Program" },
        { "96", "Hospice Quality Reporting Program" },
        { "97", "Outpatient Quality Reporting Program" },
        { "98", "Inpatient Psychiatric Facility (IPF) Quality Reporting Program" },
        { "99", "Ambulatory Surgical Center (ASC) Quality Reporting Program" },
        { "100", "Hospital Outpatient Quality Reporting Program" },
        { "101", "Hospital Inpatient Quality Reporting Program" },
        { "102", "Comprehensive Care for Joint Replacement (CJR) Model" },
        { "103", "Bundled Payments for Care Improvement (BPCI) Advanced" },
        { "104", "Oncology Care Model (OCM)" },
        { "105", "Other" }

    };

    public static string GetDescription(string qualifierCode)
    {
        return Descriptions.TryGetValue(qualifierCode, out var description)
            ? description
            : $"Unknown Contract Code {qualifierCode}";
    }

    public static bool IsValid(string transactionTypeCode)
    {
        return Descriptions.ContainsKey(transactionTypeCode);
    }
}